# Generated by Django 2.1.5 on 2019-01-13 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190113_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evalution',
            name='evalDate',
        ),
        migrations.AlterField(
            model_name='evalution',
            name='foodID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Food'),
        ),
        migrations.AlterField(
            model_name='evalution',
            name='grade',
            field=models.CharField(choices=[('1', '1 star(the worst)'), ('2', '2 stars'), ('3', '3 stars'), ('4', '4 stars'), ('5', '5 stars(the best)')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='foodfeature',
            name='foodID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Food'),
        ),
        migrations.AlterField(
            model_name='make',
            name='foodID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='foodID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Food'),
        ),
    ]
