# Generated by Django 2.1.5 on 2019-01-13 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0017_auto_20190113_0805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evalution',
            new_name='Evaluation',
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='foodID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Food'),
        ),
        migrations.AlterField(
            model_name='foodfeature',
            name='foodID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Food'),
        ),
        migrations.AlterField(
            model_name='make',
            name='foodID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='foodID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Food'),
        ),
    ]
