# Generated by Django 2.1.5 on 2019-01-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20190113_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='foodID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Food'),
        ),
        migrations.AlterField(
            model_name='make',
            name='foodID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='foodID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Food'),
        ),
    ]
